---
title: "README"
date: "`r Sys.Date()`"
author:
  - name: Arun Seetharam
  - name: Ha Vu
    affiliation: Tuteja Lab
    affiliation_url: https://www.tutejalab.org
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
---

```{r setup, include=FALSE}
options(max.print = "75")
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "assets/",
  fig.width = 8,
  prompt = FALSE,
  tidy = FALSE,
  message = FALSE,
  warning = TRUE
)
knitr::opts_knit$set(width = 75)
```

# BAPvsTrophoblast_Amnion

[Tuteja Lab](https://www.tutejalab.org), Iowa State University, Ames IA-50011

## Documentation

1. [Section 1: Input data preparation anlayses](1_input-data-prep_v2.html)
2. [Section 2: DESeq2 analyses](2_de-analyses_v2.html)
3. [Section 3: PCA plots for the datasets](3_pca-plots_v2.html)
4. [Section 4: Finding novel amnion markers](4_heatmaps_v2.html)
5. [Section 5: sn/scRNAseq data analyses](5_snRNAseq_v2.html)
5. [Section 6: Custom encrichment dataset preparation](6_custom-PCE_v2.html)

## Data availability

The data used in this study are publicly available:


| BioProject   | Assay Type | source_name                                                | replicates | treatment                                       | Publication     | Abbreviation          |
|--------------|------------|------------------------------------------------------------|------------|-------------------------------------------------|-----------------|-----------------------|
| PRJNA605646  | RNA-Seq    | Naïve H9 ESC                                               | 2          | Naive human PSC   condition                     | Io _et al_.       | nH9_Io                |
| PRJNA605646  | RNA-Seq    | Naïve H9 ESC-derived   nTE_D1                              | 2          | ABPJ treatment for 1   day                      | Io _et al_.       | H9_nTE_D1_Io          |
| PRJNA605646  | RNA-Seq    | Naïve H9 ESC-derived   nTE_D2                              | 2          | ABPJ treatment for 2   days                     | Io _et al_.       | H9_nTE_D2_Io          |
| PRJNA605646  | RNA-Seq    | term Amnion   (Cont2,3,4,4b,6,7,8,9,11,12,14,15 RNA-seq)   | 2          | ABPJ treatment for 3   days                     | Io _et al_.       | H9_nTE_D3_Io          |
| PRJNA605646  | RNA-Seq    | Naïve H9 ESC-derived   nCT_P3                              | 2          | ACE treatment                                   | Io _et al_.       | H9_nCT_P3_Io          |
| PRJNA605646  | RNA-Seq    | Naïve H9 ESC-derived   nCT_P10                             | 2          | ACE treatment                                   | Io _et al_.       | H9_nCT_P10_Io         |
| PRJNA605646  | RNA-Seq    | Naïve H9 ESC-derived   nCT_P15                             | 2          | ACE treatment                                   | Io _et al_.       | H9_nCT_P15_Io         |
| PRJNA605646  | RNA-Seq    | Naïve PSC (Guo _et al_.   Development 2017)-derived nCT_P15  | 2          | ACE treatment                                   | Io _et al_.       | cR_nCT_P15_Io         |
| PRJNA605646  | RNA-Seq    | 409B2 hiPSC-derived   nCT_P15                              | 2          | ACE treatment                                   | Io _et al_.       | iPS_nCT_P15_Io        |
| PRJNA605646  | RNA-Seq    | 1st Trimester_TSC   (Okae _et al_) (CT30)                    | 2          | Okae _et al_. Cell Stem   Cell 2018               | Io _et al_.       | CT_TSC_Okae           |
| PRJNA605646  | RNA-Seq    | nST from Naïve H9   ESC-derived nCT                        | 2          | modified from Okae et   al. Cell Stem Cell 2018 | Io _et al_.       | H9_nSCT_Io            |
| PRJNA605646  | RNA-Seq    | nEVT from Naïve H9   ESC-derived nCT                       | 2          | modified from Okae et   al. Cell Stem Cell 2018 | Io _et al_.       | H9_nEVT_Io            |
| PRJNA605646  | RNA-Seq    | Primed H9 ESC                                              | 2          | primed human PSC   condition                    | Io _et al_.       | pH9_Io                |
| PRJNA605646  | RNA-Seq    | pBAP_D1 from Primed   H9 ESC                               | 2          | MEF-CM with BAP   treatment                     | Io _et al_.       | H9_pBAP_D1_Io         |
| PRJNA605646  | RNA-Seq    | pBAP_D2 from Primed   H9 ESC                               | 2          | MEF-CM with BAP   treatment                     | Io _et al_.       | H9_pBAP_D2_Io         |
| PRJNA605646  | RNA-Seq    | pBAP_D3 from Primed   H9 ESC                               | 2          | MEF-CM with BAP   treatment                     | Io _et al_.       | H9_pBAP_D3_Io         |
| PRJNA605646  | RNA-Seq    | Cytotrophoblast at 7   gestational weeks                   | 2          | 7 gestational weeks                             | Io _et al_.       | CT_7wk                |
| PRJNA605646  | RNA-Seq    | Cytotrophoblast at 9   gestational weeks                   | 1          | 9 gestational weeks                             | Io _et al_.       | CT_9wk                |
| PRJNA605646  | RNA-Seq    | Cytotrophoblast at 11   gestational weeks                  | 1          | 11 gestational weeks                            | Io _et al_.       | CT_11wk               |
| PRJNA294733  | RNA-Seq    | H1 ESC-derived TB_BAP   D8 (large cells, >70 μm)           | 3          | BAP treatment                                   | Yabe _et al_.     | H1_BAP_D8_>70_Yabe    |
| PRJNA294733  | RNA-Seq    | H1 ESC-derived TB_BAP D8 (between   40-70 μm)              | 3          | BAP treatment                                   | Yabe _et al_.     | H1_BAP_D8_40-70_Yabe  |
| PRJNA294733  | RNA-Seq    | H1 ESC-derived TB_BAP   D8 (small cells, <40 μm)           | 3          | BAP treatment                                   | Yabe _et al_.     | H1_BAP_D8_<40_Yabe    |
| PRJNA294733  | RNA-Seq    | undifferentiated H1   ESC                                  | 3          | MEF-CM with FGF2   treatment                    | Yabe _et al_.     | H1_Yabe               |
| E-MTAB-10429 | RNA-Seq    | Blastocyst_TSC (Okae   _et al_) (BTS5, BTS11)                | 2          | Okae _et al_. Cell Stem   Cell 2018               | Sheridan _et al_. | BTS_TSC_Okae          |
| E-MTAB-10429 | RNA-Seq    | 1st Trimester_TSC   (Okae _et al_) (CT27, CT29, CT30)        | 3          | Okae _et al_. Cell Stem   Cell 2018               | Sheridan _et al_. | CT_TSC_Okae           |
| E-MTAB-10429 | RNA-Seq    | Blastocyst_EVT (Okae   _et al_) (BTS5, BTS11)                | 2          | Okae _et al_. Cell Stem   Cell 2018               | Sheridan _et al_. | BTS_EVT_Okae          |
| E-MTAB-10429 | RNA-Seq    | 1st Trimester_EVT (Okae _et al_) (CT27, CT29, CT30)          | 3          | Okae _et al_. Cell Stem   Cell 2018               | Sheridan _et al_. | CT_EVT_Okae           |
| E-MTAB-10429 | RNA-Seq    | Blastocyst_SCT (Okae   _et al_) (BTS5, BTS11)                | 2          | Okae _et al_. Cell Stem   Cell 2018               | Sheridan _et al_. | BTS_SCT_Okae          |
| E-MTAB-10429 | RNA-Seq    | 1st Trimester_TSC (Okae _et al_) (CT27, CT29, CT30)          | 3          | Okae _et al_. Cell Stem   Cell 2018               | Sheridan _et al_. | CT_SCT_Okae           |
| E-MTAB-10429 | RNA-Seq    | Organoid_villous   (Turco _et al_) (R053,   X011, X021,X035) | 4          | Turco _et al_. Nature   2018                      | Sheridan _et al_. | org_villous           |
| E-MTAB-10429 | RNA-Seq    | Organoid_EVT   (Turco _et al_) (R053,   X011, X021, x035)    | 4          | Turco _et al_. Nature   2018                      | Sheridan _et al_. | org_EVT               |
| PRJNA352339  | RNA-Seq    | undifferentiated H9   ESC, feeder free                     | 3          | mTeSR                                           | Shao _et al_.     | H9_ESC_Shao           |
| PRJNA352339  | RNA-Seq    | H9 ESC-derived   amnion-like cells (3D amniogenesis)       | 3          | Shao _et al_. Nature   Mater 2017                 | Shao _et al_.     | H9_amnion_Shao        |
| PRJNA276463  | RNA-Seq    | CC2 Amnion_18_female                                       | 1          | 18 gestational weeks                            | Roost _et al_.    | amnion_18wk           |
| PRJNA276463  | RNA-Seq    | CJ1 Amnion_9_male                                          | 2          | 9 gestational weeks                             | Roost _et al_.    | amnion_9wk            |
| PRJNA276463  | RNA-Seq    | CI1 Amnion_16_male                                         | 2          | 16 gestational weeks                            | Roost _et al_.    | amnion_16wk           |
| PRJNA276463  | RNA-Seq    | CR1 Amnion_22_male                                         | 2          | 22 gestational weeks                            | Roost _et al_.    | amnion_22wk           |
| PRJNA316992  | RNA-Seq    | Term Amnion   (Cont2,3,4,4b,6,7,8,9,11,12,14,15 RNA-seq)   | 12         | Term fetal amnion                               | Suzuki _et al_.   | amnion_term           |
| PRJNA720858  | snRNA-Seq  | H1 ESC-derived TB_BAP   D8 (20% O2)_snRNA-seq              | 2          | BAP treatment                                   | Khan _et al_.     | H1_BAP_D8_20pcO2_Khan |
| PRJNA720858  | snRNA-Seq  | H1 ESC-derived TB_BAP   D8 (5% O2)_snRNA-seq               | 2          | BAP treatment                                   | Khan _et al_.     | H1_BAP_D8_5pcO2_Khan  |
| PRJNA705594  | scRNA-Seq  | Naïve H9 ESC-derived   nTE_D2                              | 1          | ABPJ treatment                                  | Io _et al_.       | H9_sc.nTE_D2_Io       |
| PRJNA705594  | scRNA-Seq  | Naïve H9 ESC-derived   nTE_D3                              | 1          | ABPJ treatment                                  | Io _et al_.       | H9_sc.nTE_D3_Io       |
| PRJNA705594  | scRNA-Seq  | Naïve H9 ESC-derived   nCT_D5                              | 1          | ACE treatment                                   | Io _et al_.       | H9_sc.nCT_D5_Io       |
| PRJNA705594  | scRNA-Seq  | Naïve H9 ESC-derived   nCT_D10                             | 1          | ACE treatment                                   | Io _et al_.       | H9_sc.nCT_D10_Io      |
| PRJNA414247 | RNA-Seq     | undifferentiated   hESC line H9 cells                      | 2          | untreated                                       | Krendl _et al_.     | H9_Krendl          |
| PRJNA414247 | RNA-Seq     | hESC line H9 cells   after 8 hours of BMP4 treatment       | 2          | BMP4 exposed H9 cells                           | Krendl _et al_.     | H9_BMP4_8h_Krendl  |
| PRJNA414247 | RNA-Seq     | hESC line H9 cells   after 16 hours of BMP4 treatment      | 2          | BMP4 exposed H9 cells                           | Krendl _et al_.     | H9_BMP4_16h_Krendl |
| PRJNA414247 | RNA-Seq     | hESC line H9 cells   after 24 hours of BMP4 treatment      | 2          | BMP4 exposed H9 cells                           | Krendl _et al_.     | H9_BMP4_D1_Krendl  |
| PRJNA414247 | RNA-Seq     | hESC line H9 cells   after 48 hours of BMP4 treatment      | 2          | BMP4 exposed H9 cells                           | Krendl _et al_.     | H9_BMP4_D2_Krendl  |
| PRJNA414247 | RNA-Seq     | hESC line H9 cells   after 72 hours of BMP4 treatment      | 2          | BMP4 exposed H9 cells                           | Krendl _et al_.     | H9_BMP4_D3_Krendl  |

## Other datasets

Custom [`PlacentaCellEnrich`](https://placentacellenrich.gdcb.iastate.edu/)  were generated using:

1. [Xiang _et. al._](https://pubmed.ncbi.nlm.nih.gov/31830756/) dataset (NCBI BioProject:[PRJNA562548](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA562548)).
2. [Castel _et al.,_](https://pubmed.ncbi.nlm.nih.gov/33238118/) publication,  using data from [Petropoulos _et al.,_](https://pubmed.ncbi.nlm.nih.gov/27062923/) and [Zhou _et al.,_](https://pubmed.ncbi.nlm.nih.gov/31435013/) downloaded from [BitBucket](https://gitlab.univ-nantes.fr/E137833T/Castel_et_al_2020).



## Contacts

1. Project related questions: Geetu Tuteja
2. Scripts and workflow related questions: please open an [issue](https://github.com/Tuteja-Lab/BAPvsTrophoblast_Amnion/issues/new) here on GitHub.


## Publication

If you use the scripts from this repository in your research, please cite this publication:

_coming soon_
